---
- name: Criação de máquina para aplicação python
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    gcp_project: isaac-engenharia-de-redes
    gcp_cred_kind: serviceaccount
    gcp_cred_file: gcp.json
    vm_name: web-isaac-sartori
    zone: "us-central1-a"
    region: "us-central1"
    aluno: "isaac-sartori"

  tasks:
    - name: Instalando pip
      apt:
        name:
          - python-pip
          - python3-pip
        state: latest

    - name: Instalar dependências
      pip:
        name: 
          - requests
          - google-auth

    - name: Criando disco da VM
      gcp_compute_disk:
        name: "disk-{{aluno}}"
        size_gb: 20
        source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts
        zone: "{{zone}}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: disk

    - name: Obtendo informações de rede
      gcp_compute_network_info:
        filters:
          - name = default
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
      register: network

    - name: Criando endereço externo
      gcp_compute_address:
        name: "address-{{aluno}}"
        region: "{{region}}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: address

    - name: Criando instância da VM
      gcp_compute_instance:
        name: "{{vm_name}}"
        machine_type: n2-standard-2
        disks:
          - auto_delete: 'true'
            boot: 'true'
            source: "{{ disk }}"
        labels:
          environment: production
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                nat_ip: "{{ address }}"
                type: ONE_TO_ONE_NAT
        zone: "{{zone}}"
        project: "{{gcp_project}}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
